#!/bin/env bash
cluster=$(echo $1 | cut -d _ -f 1)
port=$(echo $1 | cut -d _ -f 2)
echo "$cluster $port"
echo "$(pwd)/12"
docker run --rm --name=$cluster -d -v /etc/letsencrypt:/etc/letsencrypt -v $(pwd)/$1:/etc/xray/config.json \
	-p $port:$port teddysun/xray
